name: Continuous Integration and Continuous Deployment

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      
      - name: Setting up dotnet
        uses: actions/setup-dotnet@v3
        with: 
          dotnet-version: "6.0.x"

      - name: Restoring dotnet dependencies
        run: dotnet restore

      - name: Building
        run: dotnet build -c Release --no-restore
        
    